### ISSUE TITLE
Add services to radio bridge for reading and writing firmware parameters

### ISSUE THREAD

**Issue by barulicm** [SSL-A-Team/software#184]
Use the parameter packets defined in [robot_parameters.h](https://github.com/SSL-A-Team/software-communication/blob/main/ateam-common-packets/include/robot_parameters.h)

**Comment by barulicm** [comment]
@guyfleeman, I've added a first pass at implementing this to the branch linked to this issue. I've got a couple follow up questions.

1. Which parameters use which formats?
   I need this mapping to finish implementing [GetParameterDataFormatForParameter()](https://github.com/SSL-A-Team/software/blob/f36068a46f4f5eb990ff0dc943f0877d19ec5a23/ateam_radio_bridge/src/rnp_packet_helpers.cpp#L267).

1. Is there any way for the parameter ack message to indicate that a problem happened on the robot side?

**Comment by guyfleeman** [comment]
1. Here's the expected values. We'll need to coordinate on row or column major ordering for the MATRIX_F32. Picked 5x5 since that's the biggest matrix we have rn but I think the gain matrix is smaller. Looks like the rust ordering is column-by-columns, so [C1R1 C1R2, C2R1, C2R2]. https://docs.rs/nalgebra/latest/nalgebra/base/struct.Matrix.html#method.as_mut_slice
    
    case VEL_PID_X:
      return PID_LIMITED_INTEGRAL_F32;
    case VEL_PID_Y:
      return PID_LIMITED_INTEGRAL_F32;
    case ANGULAR_VEL_PID_Z:
      return PID_LIMITED_INTEGRAL_F32;
    case VEL_CGKF_ENCODER_NOISE:
      return F32;
    case VEL_CGKF_GYRO_NOISE:
      return F32;
    case VEL_CGKF_PROCESS_NOISE:
      return F32;
    case VEL_CGFK_INITIAL_COVARIANCE:
      return F32;
    case VEL_CGKF_K_MATRIX:
      return MATRIX_F32;
      
      
2. Sure we could just do ACK and NACK as a top level field?

**Comment by guyfleeman** [comment]
Perhaps the PID type could just die? We could just send over PID+Imin+Imax and for applications that don't implement I{min,max} we they could be ignored.
